import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home ()
{
  return (
    <div className={ styles.container }>
      <Head>
        <title>Wreck Roll</title>
        <meta name="description" content="Generated by your mom" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.animate }>
        <h1 className={ styles.title }>
          WreckRoll
        </h1>
        <p className={ styles.description }>
          Rickrolling since 2021
        </p>
      </header>
    </div>
  )
}